### ISSUE TITLE
Some more resources

### ISSUE THREAD

**Issue by zmughal** [Perl-XS/notes#8]
Do you think it might be useful to have some of these in the list?
- Slides [Perl5 Memory Manglement](http://www.slideshare.net/lembark/perl5-memorymanglement)
- [Perl 5 Internals](http://www.faqs.org/docs/perl5int/) [PDF](http://perlbin.sourceforge.net/perlcompiler/perl.internals.pdf)
- Perl 5 Internals blog posts: parts [1](http://hoelz.ro/blog/perl-5-internals-part-one), [2](http://hoelz.ro/blog/perl-5-internals-part-two), [3](http://hoelz.ro/blog/perl-5-internals-part-three), [4](http://hoelz.ro/blog/perl-5-internals-part-four)

**Comment by wolfsage** [comment]
Updated, thanks!

I put the Internals and Perl5 Memory Management under a "Possibly outdated but useful" headline. They're fairly old, much could have changed, but I think there's still a lot to be learned from them.
